import type {RealityService} from './service.ts';
import type {AudienceT,MessageDraft,RepairPlan,Snapshot} from './contracts.ts';
import {Audience} from './contracts.ts';
import {adfText} from './providers.ts';
import {assert,hash,id,now,equal} from './util.ts';

export function verifiedSummary(service:RealityService,plan:RepairPlan){return plan.actions.map(action=>{const effect=service.store.effect(action.id);return `${action.provider==='calendar'?'Calendar':'Jira'}: ${effect?.state==='verified'?'verified':'not verified'} — ${action.description}${effect?.state==='verified'?` (${JSON.stringify(action.patch)})`:''}.`;});}
export class Messages {
  constructor(public service:RealityService){}
  async audienceAllowed(entityId:string,audience:AudienceT){const {config,providers}=this.service;const entity=this.service.entity(entityId);const c=config();
    if(audience.kind==='manual')return{jiraAllowed:false};
    const rule=c.sharingRules.find(r=>r.entityId===entityId&&r.audience===(audience.kind==='jira'?'jira:':'')+audience.target);
    if(audience.kind==='jira'){assert(audience.target===entity.issueKey&&rule?.allowJira,'Approve a sharing boundary for this Jira issue in Connections.');return{jiraAllowed:true};}
    if(audience.target===entity.slackChannelId)return{jiraAllowed:!!rule?.allowJira};
    if(rule)return{jiraAllowed:rule.allowJira};
    assert(/^U[A-Z0-9]+$/.test(audience.target)||audience.target===c.operatorSlackId,'The audience has no approved sharing boundary.');
    let cursor='';let found=false;for(let i=0;i<100;i++){const data=await providers.slack('conversations.members',{channel:entity.slackChannelId,limit:200,...(cursor?{cursor}:{})},true);found ||=data.members.includes(audience.target);cursor=data.response_metadata?.next_cursor||'';if(!cursor)break;if(i===99)throw new Error('Audience membership is incomplete.');}
    assert(found,'The selected Slack user cannot be established as a member of the evidence channel.');return{jiraAllowed:false};
  }
  async create(entityId:string,category:MessageDraft['category'],audienceValue:unknown){const audience=Audience.parse(audienceValue);const allowed=await this.audienceAllowed(entityId,audience);const event=this.service.currentEvent(entityId);const entity=this.service.entity(entityId);const current=this.service.store.get('current',entityId);const plan=current?this.service.plan(current.planId):undefined;
    const facts:string[]=[];
    if(category==='clarification'){assert(plan&&(plan.unresolved.length||event.unresolved.length),'This event has no unresolved facts to clarify.');facts.push(`Please confirm the ${entity.kind==='launch'?'launch date':'meeting time and location'} for ${entity.title}. We have conflicting records and need a decision from the configured owner before changing them.`);}
    else{assert(plan,'Investigate this event before drafting an update.');const summaries=verifiedSummary(this.service,plan).filter(s=>!s.startsWith('Jira:')||allowed.jiraAllowed);facts.push(...summaries);
      if(!facts.length)facts.push('No application changes have been verified for this reconciliation.');
      if(category==='consequence'&&allowed.jiraAllowed&&event.issue){facts.push(`Linked preparation task ${entity.issueKey}: ${event.issue.fields?.status?.name||'status unknown'}. Its deadline and status have not been changed by Reality Sync.`);}}
    if(audience.kind==='manual'){facts.splice(0,facts.length,'Manual communication draft. Select the facts you are authorized to share before sending outside Reality Sync.');}
    const text=category==='clarification'?facts.join('\n'):`Update for ${entity.title}:\n${facts.join('\n')}\n${category==='consequence'?'Please review any preparation work affected by this change.':''}`.trim();
    const draft:MessageDraft={id:id(),revision:id(),entityId,eventRevision:event.revision,planId:plan?.id,category,audience,text,facts,evidenceIds:plan?.claims.map(c=>c.evidenceId)||[],state:'review',createdAt:now()};this.service.store.put('draft',draft.id,draft);this.service.store.immutable('draftRevision',draft.revision,draft);return draft;
  }
  get(id:string){const d=this.service.store.get<MessageDraft>('draft',id);assert(d,'Draft not found.');return d;}
  edit(draftId:string,revision:string,text:string){const d=this.get(draftId);assert(d.revision===revision&&d.state==='review','Draft has changed or is no longer editable.');assert(text.trim().length>0&&text.length<=10000,'Message must contain 1–10000 characters.');const next={...d,text:text.trim(),revision:id()};this.service.store.put('draft',d.id,next);this.service.store.immutable('draftRevision',next.revision,next);return next;}
  dismiss(draftId:string,revision:string){const d=this.get(draftId);assert(d.revision===revision&&!['sending','verified','uncertain'].includes(d.state),'Draft cannot be dismissed in its current state.');this.service.store.put('draft',d.id,{...d,state:'dismissed'});}
  async verifyMappings(eventId:string){const event=this.service.currentEvent(eventId);const result=[];for(const a of event.event.attendees||[]){const mapping=this.service.config().attendeeMappings.find(m=>m.email.toLowerCase()===a.email.toLowerCase()&&m.verified);let verified=false;if(mapping){const data=await this.service.providers.slack('users.info',{user:mapping.slackId},true);verified=data.user?.profile?.email?.toLowerCase()===a.email.toLowerCase();}result.push({email:a.email,slackId:verified?mapping?.slackId:undefined,mapped:verified});}return{attendees:result,allMapped:result.length>0&&result.every(r=>r.mapped)};}
  async approveSend(draftId:string,revision:string,actor:string){const d=this.get(draftId);assert(actor==='operator'||this.service.config().approverSlackIds.includes(actor),'This Slack user cannot send reviewed messages.');assert(d.revision===revision,'Review the latest message revision.');assert(d.audience.kind!=='manual','External communication is a manual draft.');assert(d.state==='review','Message is not ready to send.');this.current(d);await this.audienceAllowed(d.entityId,d.audience);
    this.service.store.transaction(()=>{this.service.store.immutable('sendApproval',revision,{actor,at:now(),draftId,revision});this.service.store.put('draft',d.id,{...d,state:'approved'});this.service.store.enqueue('message',revision,{draftId,revision});});return{queued:true};}
  current(d:MessageDraft){assert(this.service.currentEvent(d.entityId).revision===d.eventRevision,'Underlying event changed. Generate a new message draft.');if(d.planId)assert(this.service.store.get('current',d.entityId)?.planId===d.planId,'A newer reconciliation superseded this draft.');}
  async send(draftId:string,revision:string){let d=this.get(draftId);assert(d.revision===revision,'Message revision superseded.');assert(this.service.store.get('sendApproval',revision),'Message requires human review and send approval.');this.current(d);await this.audienceAllowed(d.entityId,d.audience);
    if(d.planId)await this.service.sourceUnchanged(this.service.plan(d.planId));
    const event=this.service.currentEvent(d.entityId);const remote=await this.service.providers.calendarGet(event.calendarId,event.event.id);assert(hash(remote)===hash(event.event),'Calendar changed since message review. Scan again.');
    const actionId=hash(['message',revision]);let effect=this.service.store.effect(actionId);
    if(effect){const found=await this.findSent(d,effect.request.channel,effect.reference);if(found){this.finish(d,actionId,found);return;}assert(effect.state==='prepared','Send outcome is uncertain. Inspect destination; no blind retry is allowed.');}
    let channel=d.audience.target;if(d.audience.kind==='slack'&&(/^U[A-Z0-9]+$/.test(channel)||channel===this.service.config().operatorSlackId))channel=(await this.service.providers.slack('conversations.open',{users:channel})).channel.id;
    if(d.audience.kind==='jira'&&event.issue?.comments?.some((c:any)=>c.visibility)){assert(d.audience.visibility&&event.issue.comments.filter((c:any)=>c.visibility).every((c:any)=>equal(c.visibility,d.audience.visibility)),'Preserve the restrictive Jira comment visibility before posting.');}
    effect=effect||{id:actionId,kind:'message',state:'prepared',request:{draft:d,channel},observations:[],attempts:0,updatedAt:now()};this.service.store.putEffect(effect);effect.state='sending';effect.attempts++;this.service.store.putEffect(effect);this.service.store.put('draft',d.id,{...d,state:'sending'});
    try{const result=d.audience.kind==='slack'?await this.service.providers.slack('chat.postMessage',{channel,text:d.text,...(d.audience.threadTs?{thread_ts:d.audience.threadTs}:{}),unfurl_links:false,unfurl_media:false,client_msg_id:revision}):await this.service.providers.comment(channel,d.text,actionId,d.audience.visibility);
      effect.reference=result;this.service.store.putEffect(effect);const found=await this.findSent(d,channel,result);assert(found,'Message presence could not be verified.');this.finish(d,actionId,found);
    }catch(error){effect.state='uncertain';effect.error=(error as Error).message;this.service.store.putEffect(effect);this.service.store.put('draft',d.id,{...d,state:'uncertain'});throw error;}
  }
  async findSent(d:MessageDraft,channel:string,reference:any){if(d.audience.kind==='jira'){const comments=await this.service.providers.comments(channel);const actionId=hash(['message',d.revision]);return comments.find(c=>(reference?.id===c.id||c.properties?.some((p:any)=>p.key==='realitySyncAction'&&p.value===actionId))&&adfText(c.body)===d.text);}
    let cursor='';for(let page=0;page<50;page++){const data=await this.service.providers.slack(d.audience.threadTs?'conversations.replies':'conversations.history',{channel,limit:100,...(d.audience.threadTs?{ts:d.audience.threadTs}:{}),...(cursor?{cursor}:{})},true);const found=data.messages?.find((m:any)=>(reference?.ts===m.ts||m.client_msg_id===d.revision)&&m.text===d.text);if(found)return found;cursor=data.response_metadata?.next_cursor||'';if(!cursor)return undefined;}throw new Error('Message readback pagination incomplete.');}
  finish(d:MessageDraft,actionId:string,found:any){const effect=this.service.store.effect(actionId)!;effect.state='verified';effect.reference=found;effect.observations.push({at:now(),presence:true});this.service.store.transaction(()=>{this.service.store.putEffect(effect);this.service.store.put('draft',d.id,{...d,state:'verified',receipt:{at:now(),presence:true,providerReference:found.id||found.ts,readership:'unknown'}});if(d.category==='clarification'&&d.audience.kind==='slack')this.service.store.put('clarification',`${d.audience.target}:${found.ts}`,{entityId:d.entityId,channel:d.audience.target,ts:found.ts});this.service.store.log('message_verified',{draftId:d.id,actionId,mode:this.service.providers.mode});});}
  async recover(draftId:string){const d=this.get(draftId);assert(d.state==='uncertain','Only uncertain sends need readback recovery.');const actionId=hash(['message',d.revision]);const effect=this.service.store.effect(actionId)!;const found=await this.findSent(d,effect.request.channel,effect.reference);assert(found,'Presence is still unknown. No message was resent.');this.finish(d,actionId,found);}
}
