import type {RealityService} from './service.ts';
import {ReminderInput,type Reminder,type ReminderInputT,type EventRevision} from './contracts.ts';
import {eventStart,eligible,reminderOverrides} from './time.ts';
import {assert,hash,id,now,equal} from './util.ts';
import {ProviderError} from './providers.ts';
export class Reminders {
  freshDeparture?:(tripId:string,eventId:string)=>Promise<string>;
  constructor(public service:RealityService){}
  async preview(input:unknown){const parsed=ReminderInput.parse(input);const event=this.service.currentEvent(parsed.eventId);assert(eligible(event.event),'Canceled or declined meetings cannot receive new reminders.');assert(!event.unresolved.length,'Resolve the meeting facts before scheduling dependent reminders.');
    assert(!(parsed.channel==='calendar'&&parsed.rule!=='relative'),'Use Slack or the app for absolute and departure reminders. Calendar offsets are event-relative.');
    const triggerAt=await this.trigger(parsed,event);assert(Date.parse(triggerAt)>Date.now(),'Choose a future reminder time.');
    if(parsed.channel==='slack')assert(Date.parse(triggerAt)-Date.now()<=120*86400000,'Slack can schedule at most 120 days ahead.');
    if(parsed.channel==='calendar')reminderOverrides(event.event,event.defaults,parsed.minutes);
    const logicalId=hash([this.service.config().operatorSlackId||'operator',event.occurrenceKey,parsed.purpose,parsed.channel]);
    return{...parsed,id:logicalId,eventRevision:event.revision,triggerAt,existing:this.service.store.get<Reminder>('reminder',logicalId),warning:Date.parse(triggerAt)>=Date.parse(eventStart(event.event,this.service.config().preferences.timezone))?'This reminder is at or after the meeting.':undefined};
  }
  async trigger(input:ReminderInputT,event:EventRevision){if(input.rule==='absolute'){assert(input.at&&/T.*(?:Z|[+-]\d\d:\d\d)$/.test(input.at)&&Number.isFinite(Date.parse(input.at)),'Choose an absolute date/time with timezone.');return new Date(input.at).toISOString();}if(input.rule==='departure'){assert(input.tripId&&this.freshDeparture,'Choose a calculated trip first.');return this.freshDeparture(input.tripId,event.id);}return new Date(Date.parse(eventStart(event.event,this.service.config().preferences.timezone))-input.minutes*60000).toISOString();}
  async approve(input:unknown){const p=await this.preview(input);const existing=p.existing;
    if(existing&&existing.triggerAt===p.triggerAt&&existing.eventRevision===p.eventRevision&&!['failed','canceled','stale'].includes(existing.state))return existing;
    const reminder:Reminder={...ReminderInput.parse(input),id:p.id,owner:this.service.config().operatorSlackId||'operator',eventRevision:p.eventRevision,revision:id(),triggerAt:p.triggerAt,state:'approved',approvedAt:now(),providerId:existing?.providerId,providerChannel:existing?.providerChannel,calendarMinutes:existing?.calendarMinutes};
    this.service.store.transaction(()=>{this.service.store.put('reminder',reminder.id,reminder);this.service.store.immutable('reminderRevision',reminder.revision,reminder);this.service.store.enqueue('reminder',reminder.revision,{id:reminder.id,revision:reminder.revision});this.inbox(reminder,'Reminder approved');});return reminder;
  }
  inbox(r:Reminder,message:string){this.service.store.put('inbox',`reminder:${r.id}`,{id:r.id,kind:'reminder',eventId:r.eventId,message,state:r.state,triggerAt:r.triggerAt,updatedAt:now(),error:r.lastError});}
  async schedules(){let cursor='';const values:any[]=[];for(let page=0;page<100;page++){const data=await this.service.providers.slack('chat.scheduledMessages.list',{limit:100,...(cursor?{cursor}:{})},true);values.push(...data.scheduled_messages||[]);cursor=data.response_metadata?.next_cursor||'';if(!cursor)return values;}throw new Error('Slack schedule readback incomplete.');}
  async schedule(reminderId:string,revision:string){const r=this.service.store.get<Reminder>('reminder',reminderId);assert(r&&r.revision===revision,'Reminder revision superseded.');const event=this.service.currentEvent(r.eventId);assert(event.revision===r.eventRevision&&!event.unresolved.length,'Event changed after reminder approval.');
    const current=await this.service.providers.calendarGet(event.calendarId,event.event.id);assert(hash(current)===hash(event.event),'Calendar changed. Scan before scheduling.');
    if(r.rule==='departure'){const departure=await this.trigger(r,event);assert(departure===r.triggerAt,'Departure estimate changed. Review the revised reminder.');}
    if(Date.parse(r.triggerAt)<=Date.now()){r.state='missed';this.service.store.put('reminder',r.id,r);this.inbox(r,'Reminder time passed before scheduling');return;}
    try{if(r.channel==='calendar')await this.calendar(r,event);else if(r.channel==='slack')await this.slack(r);else{r.state='scheduled';}
      this.service.store.put('reminder',r.id,r);this.inbox(r,r.channel==='calendar'?'Calendar reminder setting verified':'Reminder scheduled');
    }catch(error){r.state='attention';r.lastError=(error as Error).message;this.service.store.put('reminder',r.id,r);this.inbox(r,'Reminder needs attention');throw error;}
  }
  async calendar(r:Reminder,event:EventRevision){const remote=await this.service.providers.calendarGet(event.calendarId,event.event.id);const defaults=await this.service.providers.calendarDefaults(event.calendarId);const patch=reminderOverrides(remote,defaults,r.minutes);
    const actionId=hash(['calendar-reminder',r.revision]);let effect=this.service.store.effect(actionId);
    if(!patch){r.state='verified';r.providerId=remote.id;return;}
    if(effect?.state==='sending'||effect?.state==='uncertain')throw new Error('Calendar reminder outcome remains uncertain; inspect current settings before retrying.');
    effect={id:actionId,kind:'calendar-reminder',state:'sending',request:{calendarId:event.calendarId,eventId:remote.id,patch:{reminders:patch},etag:remote.etag},observations:[],attempts:1,updatedAt:now()};this.service.store.putEffect(effect);
    try{await this.service.providers.calendarPatch(event.calendarId,remote.id,{reminders:patch},remote.etag);const result=await this.service.providers.calendarGet(event.calendarId,remote.id);assert(result.reminders?.overrides?.some(o=>o.method==='popup'&&o.minutes===r.minutes),'Calendar reminder readback failed.');effect.state='verified';effect.observations.push({at:now(),reminders:result.reminders});this.service.store.putEffect(effect);r.calendarMinutes=r.minutes;r.providerId=result.id;r.state='verified';
      // A reminder-only edit also changes the event content revision.
      this.service.store.transaction(()=>{const next={...event,event:result,revision:hash([result,event.unresolved,defaults]),verifiedAt:now(),defaults};this.service.store.put('event',event.id,next);r.eventRevision=next.revision;this.service.store.enqueue('dependency',next.revision,{eventId:event.id});});
    }catch(error){effect.state='uncertain';effect.error=(error as Error).message;this.service.store.putEffect(effect);throw error;}
  }
  async cancelSlack(r:Reminder){if(!r.providerId)return;const schedules=await this.schedules();const old=schedules.find(s=>s.id===r.providerId);if(!old){assert(Date.parse(r.triggerAt)>Date.now(),'The old Slack reminder may already have posted. Inspect the destination.');r.providerId=undefined;return;}
    assert(old.post_at*1000-Date.now()>60000,'Inside Slack’s 60-second cancellation cutoff. The old reminder may still arrive; replacement has not been scheduled.');
    const actionId=hash(['cancel-schedule',r.providerId]);const effect={id:actionId,kind:'slack-cancel',state:'sending',request:{scheduled_message_id:r.providerId,channel:r.providerChannel},observations:[],attempts:1,updatedAt:now()};this.service.store.putEffect(effect);
    await this.service.providers.slack('chat.deleteScheduledMessage',effect.request);const remaining=await this.schedules();assert(!remaining.some(s=>s.id===r.providerId),'Slack cancellation could not be verified.');effect.state='verified';this.service.store.putEffect(effect);r.providerId=undefined;
    this.service.store.put('reminder',r.id,r);
  }
  async slack(r:Reminder){const operator=this.service.config().operatorSlackId;assert(operator,'Configure the operator Slack user before scheduling.');
    const actionId=hash(['slack-reminder',r.revision]);let effect=this.service.store.effect(actionId);
    const channel=r.providerChannel||(await this.service.providers.slack('conversations.open',{users:operator})).channel.id;
    const text=`Reality Sync · ${this.service.currentEvent(r.eventId).event.summary||'Meeting'}\n${r.purpose==='departure'?'Time to leave. Travel timing is an estimate.':r.purpose==='preparation'?'Preparation reminder.':'Your meeting is coming up.'}\nReference ${r.id.slice(0,8)} / ${r.revision.slice(0,8)}`;
    const request={channel,post_at:Math.floor(Date.parse(r.triggerAt)/1000),text};
    if(effect){const matches=(await this.schedules()).filter(s=>s.channel_id===channel&&s.post_at===request.post_at&&s.text===text);if(matches.length===1){r.providerId=matches[0].id;r.providerChannel=channel;r.state='verified';effect.state='verified';effect.reference=matches[0];this.service.store.putEffect(effect);return;}
      assert(effect.state==='prepared','Scheduled message outcome uncertain; no duplicate schedule was created.');}
    if(r.providerId)await this.cancelSlack(r);
    effect={id:actionId,kind:'slack-reminder',state:'sending',request,observations:[],attempts:1,updatedAt:now()};this.service.store.putEffect(effect);
    try{const result=await this.service.providers.slack('chat.scheduleMessage',request);r.providerId=result.scheduled_message_id;r.providerChannel=channel;this.service.store.put('reminder',r.id,r);effect.reference=result;this.service.store.putEffect(effect);
      const exists=(await this.schedules()).find(s=>s.id===r.providerId&&s.post_at===request.post_at&&s.text===text);assert(exists,'Scheduled reminder presence could not be verified.');effect.state='verified';this.service.store.putEffect(effect);r.state='verified';
    }catch(error){effect.state='uncertain';effect.error=(error as Error).message;this.service.store.putEffect(effect);throw error;}
  }
  async cancel(reminderId:string){const r=this.service.store.get<Reminder>('reminder',reminderId);assert(r,'Reminder not found.');if(r.channel==='slack')await this.cancelSlack(r);
    if(r.channel==='calendar'&&r.calendarMinutes!==undefined){const event=this.service.currentEvent(r.eventId);const remote=await this.service.providers.calendarGet(event.calendarId,event.event.id);const overrides=remote.reminders?.overrides||[];assert(remote.reminders?.useDefault===false,'Calendar reminder settings changed; review them manually.');const next=overrides.filter(o=>!(o.method==='popup'&&o.minutes===r.calendarMinutes));
      const effectId=hash(['cancel-calendar-reminder',r.revision]);const effect={id:effectId,kind:'calendar-cancel',state:'sending',request:{reminders:{useDefault:false,overrides:next},etag:remote.etag},observations:[],attempts:1,updatedAt:now()};this.service.store.putEffect(effect);await this.service.providers.calendarPatch(event.calendarId,remote.id,{reminders:effect.request.reminders},remote.etag);const actual=await this.service.providers.calendarGet(event.calendarId,remote.id);assert(equal(actual.reminders?.overrides,next),'Calendar cancellation readback failed.');effect.state='verified';this.service.store.putEffect(effect);}
    r.state='canceled';this.service.store.put('reminder',r.id,r);this.inbox(r,r.channel==='calendar'&&r.calendarMinutes===undefined?'App tracking stopped; pre-existing native reminder preserved':'Reminder canceled');}
  async maintain(eventId:string){const event=this.service.currentEvent(eventId);for(const r of this.service.store.all<Reminder>('reminder').filter(r=>r.eventId===eventId&&!['canceled','delivered','missed'].includes(r.state))){
    if(!eligible(event.event)||(r.purpose==='preparation'&&event.issue?.fields?.status?.statusCategory?.key==='done')){try{await this.cancel(r.id);}catch(error){r.state='attention';r.lastError=(error as Error).message;this.service.store.put('reminder',r.id,r);this.inbox(r,'Cancellation needs attention');}continue;}
    if(r.eventRevision===event.revision)continue;
    if(event.unresolved.length){r.state='stale';r.lastError='Meeting facts are unresolved. Existing provider notifications may still arrive.';}
    else if(r.rule==='absolute'){r.eventRevision=event.revision;r.lastError=Date.parse(r.triggerAt)>=Date.parse(eventStart(event.event))?'The absolute reminder is at or after the revised meeting.':undefined;}
    else if(r.channel==='calendar'){r.eventRevision=event.revision;r.triggerAt=await this.trigger(r,event);r.state='verified';}
    else if(this.service.config().preferences.maintainRelative){try{const triggerAt=await this.trigger(r,event);if(Date.parse(triggerAt)<=Date.now()){r.state='attention';r.lastError='Revised reminder is in the past; review the existing provider schedule.';}else{r.triggerAt=triggerAt;r.eventRevision=event.revision;r.revision=id();r.state='approved';this.service.store.immutable('reminderRevision',r.revision,r);this.service.store.enqueue('reminder',r.revision,{id:r.id,revision:r.revision});}}catch(error){r.state='stale';r.lastError=(error as Error).message;}}
    else{r.state='stale';r.lastError='Automatic maintenance is disabled. Review the changed meeting.';}
    this.service.store.put('reminder',r.id,r);this.inbox(r,'Reminder dependency updated');}
  }
  async tick(startup=false){const missed=[];for(const r of this.service.store.all<Reminder>('reminder')){if(r.channel==='app'&&r.state==='scheduled'&&Date.parse(r.triggerAt)<=Date.now()){r.state=startup||Date.now()-Date.parse(r.triggerAt)>60000?'missed':'delivered';this.service.store.put('reminder',r.id,r);if(r.state==='missed')missed.push(r.id);else this.inbox(r,'Reminder is due');}}
    if(missed.length)this.service.store.put('inbox',`missed:${hash(missed)}`,{id:hash(missed),kind:'missed',message:`${missed.length} reminders passed while the app was inactive.`,at:now(),reminderIds:missed});
  }
  async preparation(eventId:string,start:string){const event=this.service.currentEvent(eventId);assert(event.issue,'Choose an explicitly linked Jira issue.');assert(!event.unresolved.length,'Resolve the meeting first.');assert(event.issue.fields?.status?.statusCategory?.key!=='done','The linked task is already complete.');const end=new Date(Date.parse(start)+this.service.config().preferences.prepMinutes*60000).toISOString();assert(Date.parse(start)>Date.now()&&Date.parse(end)<=Date.parse(eventStart(event.event,this.service.config().preferences.timezone)),'Choose a future preparation block ending before the meeting.');const available=await this.service.providers.freebusy(event.calendarId,start,end);return{eventId,eventRevision:event.revision,start,end,available,issueKey:event.issue.key,summary:`Prepare: ${event.issue.fields?.summary||event.issue.key}`};}
  async approveBlock(eventId:string,start:string,eventRevision:string){const preview=await this.preparation(eventId,start);assert(preview.available,'The calendar is busy during this preparation block.');assert(preview.eventRevision===eventRevision,'Preparation preview is stale.');const blockId=hash(['prep',eventId,start]);const event=this.service.currentEvent(eventId);const request={id:blockId,summary:preview.summary,description:`Reality Sync preparation for ${preview.issueKey}.`,start:{dateTime:preview.start,timeZone:this.service.config().preferences.timezone},end:{dateTime:preview.end,timeZone:this.service.config().preferences.timezone},reminders:{useDefault:false,overrides:[{method:'popup',minutes:0}]},extendedProperties:{private:{realitySync:blockId}}};
    this.service.store.immutable('block',blockId,{id:blockId,eventId,eventRevision,request,approvedAt:now()});this.service.store.enqueue('block',blockId,{blockId});return{blockId};}
  async createBlock(blockId:string){const block=this.service.store.get('block',blockId);assert(block,'Block approval missing.');const event=this.service.currentEvent(block.eventId);assert(event.revision===block.eventRevision,'Preparation event revision changed.');const effectId=hash(['block',blockId]);let effect=this.service.store.effect(effectId);
    if(effect){try{const existing=await this.service.providers.calendarGet(event.calendarId,blockId);assert(existing.extendedProperties&&equal(existing.start,block.request.start),'Existing preparation block differs.');effect.state='verified';effect.reference=existing;this.service.store.putEffect(effect);return;}catch(error){if(!(error instanceof ProviderError&&error.status===404))throw error;}}
    assert(await this.service.providers.freebusy(event.calendarId,block.request.start.dateTime,block.request.end.dateTime),'Preparation slot is no longer available.');effect={id:effectId,kind:'prep-block',state:'sending',request:block.request,observations:[],attempts:(effect?.attempts||0)+1,updatedAt:now()};this.service.store.putEffect(effect);
    await this.service.providers.createBlock(event.calendarId,block.request);const observed=await this.service.providers.calendarGet(event.calendarId,blockId);assert(observed.id===blockId,'Preparation block not found on reread.');effect.state='verified';effect.reference=observed;this.service.store.putEffect(effect);this.service.store.log('preparation_verified',{blockId,eventId:event.id});}
}
